[package]
name = "zed_gdscript"
version = "0.6.0"
edition = "2021"
publish = false
license = "MIT"

[lib]
path = "src/gdscript.rs"
crate-type = [ "cdylib",]

[dependencies]
zed_extension_api = "0.7.0"

[profile.release]
strip = true
