name = "GDShader"
grammar = "gdshader"
path_suffixes = ["gdshader"]
line_comments = ["// "]
block_comment = ["/* ", " */"]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
]
